
INC = /usr/include/python3.8

hello.so: hello.o
	gcc -shared -o hello.so hello.o

hello.o: hello.c
	gcc -fPIC -o hello.o -c hello.c -I $(INC)

hello.c: hello.pyx
	cython -3 hello.pyx -o hello.c

.PHONY: clean
clean:
	rm -rf *.so *.o *.c

